import {
  AamAchaar,
  Aamras,
  AlooParatha,
  Appam,
  Bebincha,
  BhaghareBaigan,
  BharwaBhindi,
  BiseBeleBhath,
  ButterChicken,
  ChholeBhature,
  Chiken,
  ChickenChettinad,
  ChickenDhansak,
  ChickenTikka,
  ChingriMalaiCurry,
  CoconutLadoo,
  CrabCurry,
} from "./foodImage/FoodImage";

export const foodList = [
  { itemName: "Aam Achaar", price: "25", details: "AamAchaar", src: AamAchaar },
  { itemName: "Aamras", price: "30", details: "aamras", src: Aamras },
  { itemName: "Aloo Paratha", price: "40", details: "AlooParatha", src: AlooParatha },
  { itemName: "Appam", price: "45", details: "Appam", src: Appam },
  { itemName: "Bebincha", price: "56", details: "Bebincha", src: Bebincha },
  { itemName: "Bhaghare Baigan", price: "30", details: "BhaghareBaigan", src: BhaghareBaigan },
  { itemName: "Bharwa Bhindi", price: "35", details: "BharwaBhindi", src: BharwaBhindi },
  { itemName: "Bise Bele Bhath", price: "20", details: "aaBiseBeleBhathmras", src: BiseBeleBhath },
  { itemName: "Butter Chicken", price: "55", details: "ButterChicken", src: ButterChicken },
  { itemName: "Chhole Bhature", price: "40", details: "ChholeBhature", src: ChholeBhature },
  { itemName: "Chicken Chettinad", price: "60", details: "ChickenChettinad", src: ChickenChettinad },
  { itemName: "Chicken", price: "50", details: "aamras", src: Chiken },
  { itemName: "Chicken Dhansak", price: "65", details: "ChickenDhansak", src: ChickenDhansak },
  { itemName: "Chicken Tikka", price: "50", details: "ChickenTikka", src: ChickenTikka },
  { itemName: "Chingri Malai Curry", price: "65", details: "ChingriMalaiCurry", src: ChingriMalaiCurry },
  { itemName: "Coconut Ladoo", price: "30", details: "CoconutLadoo", src: CoconutLadoo },
  { itemName: "Crab Curry", price: "65", details: "CrabCurry", src: CrabCurry },
  
];
